default: &default
  contact_form_email_to: "sales@novi-tec.com"
  new_orders_email_to: "sales@novi-tec.com"
  send_email_from: "sales@novi-tec.com"
  message_id_domain: "novi-tec.com"
  smtp_port: 587
  smtp_server: "gator4236.hostgator.com"
  
development:
  <<: *default
  host: "http://10.50.55.30:3000"

test:
  <<: *default

production:
  <<: *default
  host: "https://novi-tec.com"
